### ISSUE TITLE
Making the App Responsive and Look Good on Mobile Devices

### ISSUE THREAD

**Issue by MarcoMorawec** [waywho/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured this step out :)

**Comment by waywho** [comment]
I just added a viewport meta tag <meta name="viewport....> in my application.html.erb. For extra safety, I have also added couple of CSS @viewport tags. Please see my latest commit. It is also pushed up to Heroku and I checked on my mobile that it is nicely zoomed in.

**Comment by MarcoMorawec** [comment]
Nice one @waywho :+1: 

Quick suggestion: move your viewport meta tag from your current line 4 to right below the <%= csrf_meta_tags %>. That way you're code is a bit cleaner.

**Comment by waywho** [comment]
done!

**Comment by MarcoMorawec** [comment]
Nice!

Make sure to close the issue, since you're done with it.
